### ISSUE TITLE
Getting 403 connecting to Custom Store on Laravel Forge

### ISSUE THREAD

**Issue by Lab385** [FosterCommerce/shipstation-connect#57] opened 2023-10-24 08:57 UTC
- I've tried my luck with Shipstation support but they're insisting I'm doing it wrong.
- Clicking the Test Connection button works, but 'Connect' returns 'Request failed with status code 403'
- A curl with basic auth works fine.
- Ive set up Shipping statuses and Matrix field.

As Laravel Forge runs Nginx I wonder if it's not passing the auth, so tried adding this to location in nginx conf but to no effect:

```
proxy_set_header Authorization $http_authorization;
proxy_pass_header  Authorization;
```

**Comment by johnnynotsolucky** [comment] 2023-10-25 08:42
@Lab385 could you provide some more information so we can investigate the issue more thoroughly:

- Version of Craft
- Version of Craft Commerce
- Version of this plugin

Could you also confirm 

- that the URL you've captured in "URL to Custom XML Page" on the ShipStation custom store form matches the URL provided by the plugin in the plugins settings page
- and, that you can make a request to the export endpoint

The plugin doesn't output an HTTP 403. If the username/password combination is incorrect you should see an HTTP 401 response instead. 

A request such as the following can be used to test whether exports work correctly:

```bash
curl --location 'https://<your host>/actions/shipstationconnect/orders/process?action=export' \
  --header 'Authorization: Basic <username:password>'
```

The authorization header value is a base64 encoded string of `username:password`.

**Comment by Lab385** [comment] 2023-10-25 09:17
Hi @johnnynotsolucky

Craft Pro 4.5.9
Craft Commerce 4.3.1
ShipStation Connect 2.0.3

Yes, I’ve copied the link straight out of the Shipstation Connect plugin
and the curl returns a list of orders.

**Comment by johnnynotsolucky** [comment] 2023-10-26 06:16
@Lab385 it seems like the problem lies somewhere between your site and ShipStation. You'll need to figure out where the fault is.

As a first step, you can confirm that ShipStations requests are indeed reaching your server: 

In Laravel Forge, you can view nginx logs by 
- Navigating the relevant server, 
- Selecting "Logs" 
- Then from the "View Log" drop down, choosing either Nginx Error or Nginx Access logs. 
 
Attempt to create the connection in ShipStation, refresh the access log and verify that a new access log appears. If it errored, you should still see the log, but with an error HTTP code. Then you can have a look at the error log for potential causes.

I'm going to close this for now because it looks like it's not a problem caused by the plugin directly.

However, please reach out to me on the Craft Discord, I have the same handle as on Github, and I can assist further.

**Closed by johnnynotsolucky** 2023-10-26 06:16 UTC

**Comment by terryupton** [comment] 2024-04-16 14:28
@Lab385 did you manage to resolve this as I am seeing similar issues.

**Comment by terryupton** [comment] 2024-04-16 14:33
Did you manage to resolve this @Lab385 as I am seeing the same issue.

**Comment by Lab385** [comment] 2024-04-17 00:20
> Did you manage to resolve this @Lab385 as I am seeing the same issue.

@terryupton it was an issue with the actual account, from what we could see. I created a new test account, the integration worked fine, so we moved everything across.

**Comment by johnnynotsolucky** [comment] 2024-04-17 13:21
@terryupton what specific issue are you seeing?

The steps in the [comment above](https://github.com/FosterCommerce/shipstation-connect/issues/57#issuecomment-1778791412) should help you diagnose where the problem lies.

**Comment by terryupton** [comment] 2024-04-17 14:52
Hey @johnnynotsolucky and @Lab385 - thanks for the replies.
I managed to resolve this by adding the .htaccess file with the following:
```
CGIPassAuth On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```
